#!/usr/bin/env python

import sys

import mysystem #the building/testing/analyzing system

def main():
    "The main function is responsible for `everything`"
    s = mysystem.System(sys.argv[1:]) #load config and prepare system
    s.force_compress() #force compression of working directory
    s.compress_wd() #compress the working directory
    sys.exit(1)

## Run code
main()
