#!/usr/bin/env python

import sys

import mysystem #the building/testing/analyzing system

def main():
    "The main function is responsible for `everything`"
    s = mysystem.System(sys.argv[1:]) #load config and prepare system
    s.build() #builds a new network
    s.test_train_set() #test the network with the training set
    s.test_test_set() #test the network with the test set
    #s.test_validation_set() #test the network with the validation set
    s.analyze() #analyze the results produce by earlier steps
    s.compress_wd() #compress the working directory
    sys.exit(1)

## Run code
main()
